db.restaurants.find()
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,"address.zipcode":1,_id:0})
db.restaurants.find({borough: 'Bronx'})
db.restaurants.find({borough: 'Bronx'}).limit(5)
db.restaurants.find({borough: 'Bronx'}).skip(5).limit(5)
db.restaurants.find({"grades.score": {$gt:90}})
db.restaurants.find( { $and: [ {"grades.score": {$gt:80} }, {"grades.score": {$lt:100}} ] } )
db.restaurants.find ( {"address.coord":{ $lt: -95.754168}} )
db.restaurants.find ( {$and: [ {  cuisine: {$not:{$regex:"American"}}} , { "grades.score": {$gt:70}} ]} )
db.restaurants.find( { $and: [  {  cuisine: {$not:{$regex:"American"}}} ,{"grades.score": {$gt:70} }, {"address.coord.0":{ $lt: -65.754168}} ] } )
db.restaurants.find( { $and: [  {  cuisine: {$not:{$regex:"American"}}} ,{"grades.grade": 'A' }, {"borough":{$not:{$regex:"Brooklyn"}}} ] } ).sort( { "cuisine": -1 } )
db.restaurants.find({ name: {$regex:"^Wil"}} ,{restaurant_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({ name: {$regex:"ces$"}} ,{restaurant_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({ name: {$regex:"Reg"}} ,{restaurant_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({$and:[{borough: 'Bronx'},{$or:[{  cuisine: {$regex:"American"}},{  cuisine: {$regex:"Chinese"}}]}]})
db.restaurants.find({ "borough": { "$in": [/Staten Island/,/Bronx/,/Queens/,/Brooklyn/] } } ,{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({ "borough": { "$nin": [/Staten Island/,/Bronx/,/Queens/,/Brooklyn/] } } ,{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({ "grades.score": {$lte:10}} ,{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({$and:[{"preparen peix atribute?":/fish/},{ "cuisine": { "$nin": [/American/,/Chinees/] } }]} ,{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find(  {"grades" : {$elemMatch: {"grade":"A", "score":11, "date": ISODate("2014-08-11T00:00:00Z") }}}, {_id:0, restaurant_id:1, name:1, grades:1})
db.restaurants.find( {$and: [{"grades.1.grade":"A"}, {"grades.1.score": 9},{"grades.1.date": ISODate("2014-08-11T00:00:00Z")}]}, {_id:0, restaurant_id:1, name:1, grades:1} )
db.restaurants.find( {$and : [{"address.coord.1": {$gt : 42}}, {"address.coord.1": {$lte : 52}}]}, {_id:0, restaurant_id:1, name:1, address:1} )
db.restaurants.find().sort({name:1})
db.restaurants.find().sort({name:-1})
db.restaurants.find().sort({cuisine:1, borough:-1})
db.restaurants.find({ "address.street": { $exists: false } })
db.restaurants.find({"address.coord": {$type : "double"}})
db.restaurants.find({ "grades.score": {$mod: [ 7, 0 ]}} ,{_id:0, restaurant_id:1, name:1, grades:1})
db.restaurants.find({ name: {$regex:"mon"}} ,{_id:0,name:1,borough:1,"address.coord":1})
db.restaurants.find({ name: {$regex:"^Mad"}} ,{_id:0,name:1,borough:1,"address.coord":1})
